#!/bin/bash

zwierze=kot

echo "Jaki mały ${zwierze}ek!!!"
echo Jaki" mały $zwierze"ek!!!
echo 'J'aki" mały $zwierze"ek'!!!'

echo 'Adam Mickiewicz - "Pan Tadeusz"'
echo "Adam Mickiewicz - \"Pan Tadeusz\""
echo "Adam Mickiewicz - "'"Pan Tadeusz"'

echo "Baldur's Gate"
